import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/store/auth-provider";
import { MessageProvider } from "@/store/message-provider";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
            <AuthProvider>
              <MessageProvider>
                <Header>
                  {children}
                </Header>
              </MessageProvider>
            </AuthProvider>
          </ThemeProvider>
        </body>
    </html>
  );
}
